name: Build Flutter APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
      
      - name: Fix Android Embedding v1 to v2
        run: |
          grep -rl 'io.flutter.app' android/ | xargs sed -i 's/io.flutter.app.FlutterApplication/io.flutter.embedding.android.FlutterApplication/g' || true
          grep -rl 'io.flutter.app' android/ | xargs sed -i 's/io.flutter.app.FlutterActivity/io.flutter.embedding.android.FlutterActivity/g' || true
      
      - name: Get Packages
        run: flutter pub get
          
      - name: Build APK
        run: flutter build apk --release
        
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
